# Generated by Django 3.2.8 on 2021-11-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('cod_actividad', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('tipo_actividad', models.CharField(choices=[('extremo', 'extremo'), ('disciplina', 'disciplina')], default='disciplina', max_length=12)),
                ('clasificacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('localidad', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('dni_profesional', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('rol', models.CharField(choices=[('admi', 'Administrador'), ('user', 'Usuario')], default='user', max_length=4)),
                ('email', models.EmailField(default='valle@gmail.com', max_length=254)),
                ('contrasena', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('rol', models.CharField(choices=[('admi', 'Administrador'), ('user', 'Usuario')], default='user', max_length=4)),
                ('email', models.EmailField(default='galan@gmail.com', max_length=254)),
                ('contrasena', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.actividad')),
                ('dni_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.actividad')),
                ('dni_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.profesional')),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.lugar')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.categoria'),
        ),
    ]
