# Generated by Django 3.2.8 on 2021-12-01 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('cod_actividad', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('list_actividad', models.CharField(choices=[('yoga', 'yoga'), ('golf', 'golf'), ('tenis', 'tenis'), ('tenis de mesa', 'tenis de mesa'), ('padel', 'padel'), ('ejercicio al agua', 'ejercicio al agua'), ('parkur', 'parkur'), ('trekking', 'trekking'), ('rappel', 'rappel'), ('roller skating', 'roller skating'), ('montañismo', 'montañismo')], default='disciplina', max_length=20)),
                ('list_localidad', models.CharField(choices=[('Cochinoca', 'Cochinoca'), ('Dr. Manuel Belgrano', 'Dr. Manuel Belgrano'), ('El Carmen', 'El Carmen'), ('Humahuaca', 'Humahuaca'), ('Ledesma', 'Ledesma'), ('Palpalá', 'Palpalá'), ('Rinconada', 'Rinconada'), ('San Antonio', 'San Antonio'), ('San Pedro', 'San Pedro'), ('Santa Bárbara', 'Santa Bárbara'), ('Santa Catalina', 'Santa Catalina'), ('Susques', 'Susques'), ('Tilcara', 'Tilcara'), ('Tumbaya', 'Tumbaya'), ('Valle Grande', 'Valle Grande'), ('Yavi', 'Yavi')], default='Dr. Manuel Belgrano', max_length=100)),
                ('direccion_club', models.CharField(max_length=50)),
                ('nombre_club', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('dni_profesional', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(default='valle@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('rol', models.CharField(choices=[('admi', 'Administrador'), ('user', 'Usuario')], default='user', max_length=4)),
                ('email', models.EmailField(default='galan@gmail.com', max_length=254)),
                ('contrasena', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.actividad')),
                ('dni_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.actividad')),
                ('dni_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepNoConvencional.profesional')),
            ],
        ),
    ]
